### ISSUE TITLE
About python test scripts and SyncBN usage

### ISSUE THREAD

**Issue by Spritea** [vacancy/Synchronized-BatchNorm-PyTorch#21]
Hi,

Nice work！But when I run this test file https://github.com/vacancy/Synchronized-BatchNorm-PyTorch/blob/master/tests/test_numeric_batchnorm.py , it gives me following output.
```
F
======================================================================
FAIL: testNumericBatchNorm (__main__.NumericTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_numeric_batchnorm.py", line 51, in testNumericBatchNorm
    self.assertTensorClose(b_var1.data, b_var2.data)
  File "/home/cws/Download/Synchronized-BatchNorm-PyTorch/sync_batchnorm/unittest.py", line 28, in assertTensorClose
    self.assertTrue(torch.allclose(x, y), message)
AssertionError: False is not true : Tensor close check failed
adiff=0.0003001689910888672
rdiff=0.02449820376932621

----------------------------------------------------------------------
Ran 1 test in 0.157s

FAILED (failures=1)
```
And other 2 test python files give me similar output. I'm not sure whether this is expected.
**Version**: Pytorch1.0, cuda9.0

========
Then I use SyncBN in my code, and everything seems fine( at least from ouput, like loss, accuracy, etc.) Specificly, I do this in following methods.
- replace all `nn.BatchNorm2d` in model definition with `SynchronizedBatchNorm2d`
- replace `torch.nn.DataParallel` with `DataParallelWithCallback`
- no change to loss function, just the same as the situation when training the model with 1 GPU

Is this correct way to use SyncBN here? Do I have some method to confirm SyncBN works?

Thanks

**Comment by vacancy** [comment]
1. Yes. We do find that our implementation has some numeric issue. It seems to be less numerically stable than the pytorch built-in BN. But in our experiments, empirically, it does not hurt the performance.
2. Yes. You did it correctly!

I am closing this issue for now. Feel free to reopen if you have further questions.
